on: [push, pull_request]

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        monero: [ 0.17.3.0, 0.17.3.2, 0.18.0.0 ]

    services:
      monerod:
        image: ghcr.io/farcaster-project/containers/monerod:${{ matrix.monero }}
        env:
          NETWORK: regtest
          MONEROD_RPC_PORT: 18081
          MONEROD_ZMQ_PORT: 18082
          OFFLINE: --offline
          DIFFICULTY: 1
        ports:
        - 18081:18081
        - 18082:18082
      monero-wallet-rpc:
        image: ghcr.io/farcaster-project/containers/monero-wallet-rpc:${{ matrix.monero }}
        env:
          MONERO_DAEMON_ADDRESS: monerod:18081
          MONERO_DAEMON_HOST: monerod:18081
          WALLET_RPC_PORT: 18083
        ports:
        - 18083:18083

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
